title: CV | Chuang.Li
description:  My CV.
url: https://hython.com/cv
baseurl: ''
theme_skin: gold

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
